version: '3.7'
services:
  redis:
    image: ${DOCKER_USERNAME}/msg_redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  spring:
    depends_on: [ redis ]
    image: ${DOCKER_USERNAME}/msg_spring:latest
    restart: always
    container_name: spring
    ports:
      - "8282:8282"