spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/ssg
    url: jdbc:mysql://3.37.89.84:3306/ssg
    username: root
    password: msg0417
    #password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.type: debug
    p6spy: info

springdoc:
  #packages-to-scan: com.spharos.msg
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

JWT:
  SECRET_KEY: ssglclonecodingtesttesttestssglclonecodingtesttesttest
  access-token-expiration: 8640000
  refresh-token-expiration: 8640000