name: Build Test

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        env:
          DB_ADDRESS: jdbc:mysql://db.sssg.shop:3306/ssg
          DB_USER: root
          DB_PASSWORD: msg0417
          REDIS_DB_ADDRESS: localhost
          REDIS_PORT: 6379
        run: ./gradlew build
