name: Deploy Spring Container
on:
  push:
    branches: [ main, dev ]

jobs:
  check-file-and-run-script:
    runs-on: ubuntu-latest
    outputs:
      file-changed: ${{ steps.check-file.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes in a specific file
        id: check-file
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'src'; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi
  recreate-spring-image:
    needs: check-file-and-run-script
    if: needs.check-file-and-run-script.outputs.file-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Recreate Spring Image
        run: echo "변경점이 있기 때문에 재배포를 시작합니다."

      - name: Checkout action
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push - spring
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_spring
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/msg_spring:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max